### ISSUE TITLE
关于环境搭建遇到的问题

### ISSUE THREAD

**Issue by czs0x55aa** [ICT-BDA/EasyML#10]
1.通过百度云下的EML包，运行`run_containers.sh`时会因为`nkxujun/emlsql`报错，通过`docker images`看到本地的名字是`nkxujun/mysql_eml`，替换过后可以运行

2.在`Configure local hosts`步骤中，贴了张hosts的配置图，有点误导性，实际上应该参照`run_containers.sh`中指定的ip来配置吧

**3.按照QuickStart的流程执行，直到最后一步访问http://hadoop-master:18080/EMLStudio/，页面能正常打开，但是其它请求都返回500.（未解决）**

**Comment by sinllychen** [comment]
Hi，您好，首先感谢您的关注，关于您的问题：

1、抱歉，这个问题昨天也有人向我们反馈了，确实如您所说，目前我们已经重新上传了一版，但是忘记更新到QuickStart.md里面了，我们这下修改一下。

2、这个host地址和run_containers.sh中各个容器的host是不一样的。这个host是你安装docker的服务器地址，而run_containers.sh中的host是docker中的虚拟网卡给各个容器的虚拟地址。

3、您网页打不开的原因应该是host配置错了。您可以将您的主机地址替换hadoop-master，尝试一下。

祝好！

**Comment by czs0x55aa** [comment]
@sinllychen 
你好，我搭建完已经能访问到`http://hadoop-master:18080/EMLStudio/`页面了，说明hosts配置没有问题。
但是在执行登陆等操作的时候会返回500错误，这个错误应该是服务器端的原因吧？

我比较困惑的一个地方，`http://hadoop-master:18080`应该是运行在docker里面的吧？所以本地配置IDEA开发环境似乎没有用？

**Comment by sinllychen** [comment]
@czs0x55aa docker里面主要是给您搭建好运行EML的hadoop集群、mysql、oozie等一些环境，您可以通过IDEA在本地上直接运行EML工程，从而进行EML工程调试与开发，工程的一些配置信息在https://github.com/ICT-BDA/EasyML/blob/master/src/main/java/server-config.xml 这个文件中。

上述您遇到的登入返回500，麻烦您检查一下您搭建的mysql服务是否启动并能够正常访问？

**Comment by sinllychen** [comment]
@czs0x55aa  
刚您说的Configure local hosts 这个中的host确实是您安装docker的主机地址（若是linux安装的docker则是Linux的主机地址，若是windows docker安装则是windows的主机地址），和run_container.sh中的container地址不一样的。至于您为什么能访问到首页有可能是浏览器缓存的原因。

**Comment by czs0x55aa** [comment]
@sinllychen 谢谢您的解答，确实使用localhost是能访问到。不过500的问题还没找到原因，我明天再找找原因。
目前已确认mysql运行正常（进mysql查看过，并且本地IDEA启动的话是可以登陆的）。

非常感谢你们的工作。
另外希望文档方面能够逐步完善。

**Comment by sinllychen** [comment]
@czs0x55aa  感谢您的建议与支持，我们后续会不断完善系统相关文档，如您在后续开发或部署上有任何问题，欢迎和我们交流。

**Comment by czs0x55aa** [comment]
@sinllychen 你好，QuickStart里面提供的百度网盘地址失效了

**Comment by sinllychen** [comment]
@czs0x55aa 抱歉，我们在修改您之前反馈的run_containers.sh这个问题，此前的错误版本我们已经删除，因为百度网盘上传的是zip包，我们的zip包较大，所以估计需要一段时间才能完全上传。麻烦您稍微等待一下，多谢！

**Comment by czs0x55aa** [comment]
@sinllychen 
打扰了，遇到了新的问题，不知如何解决
在执行Job中的example的时候出错，以下是Oozie中给出的Error Message。
```
JA009: Permission denied: user=czs0x55aa, access=EXECUTE, inode="/tmp/hadoop-yarn/staging/czs0x55aa/.staging/job_1497590592086_0005":root:supergroup:drwxrwx---	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:319)	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkTraverse(FSPermissionChecker.java:259)	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:205)	at org.apache.hadoop.hdf
```

**Comment by nkzhlee** [comment]
@czs0x55aa 请问您cluster后台环境和编译器执行的环境是在同一台机器上的么？

**Comment by czs0x55aa** [comment]
@nkzhlee 
你好，我目前的所有操作都在同一台机子上执行的。编译器执行的环境是指什么？

**Comment by nkzhlee** [comment]
@czs0x55aa 编译执行的环境就是你IDEA编译运行EMLStudio的环境。如果都是在同一台机器上，应该不会有问题。您使用的是Window还是Mac？执行示例程序会不会出问题呢？

**Comment by czs0x55aa** [comment]
@nkzhlee 
系统是ubuntu 16.04，IDEA里JDK和docker里的版本不一致，和这个有关系？

**Comment by nkzhlee** [comment]
@czs0x55aa 这个应该跟JDK没有关系，因为关系到主机和docker虚拟机、docker虚拟机之间的交互，涉及到的环境有很多，可能是这中间出现了HDFS访问的权限问题。建议使用example中的示例程序测试一下，然后可以把测试结果发给我，我们一起找下原因。因为我们没有用Ubuntu测试过，所以和Ubuntu系统有没有关系并不清楚，欢迎补充解决方案。

**Comment by czs0x55aa** [comment]
@nkzhlee 
请问你说的example是指哪个程序？

**Comment by thincamel** [comment]
参照完成了部署，但oozie服务以及对应页面无法访问

**Comment by sinllychen** [comment]
@thincamel  您好，您在安装oozie的过程中有出什么错误吗？如果有错误的话，能麻烦把日志放上来吗？

**Comment by czs0x55aa** [comment]
@thincamel 
我在电脑重启后也遇到过oozie进不去的情况，发现是mysql没有运行。
不确定和你的情况是否相同，可以先检查下mysql的容器是否启动了。

**Comment by czs0x55aa** [comment]
@nkzhlee @sinllychen 
之前我在ubutnu上部署的，EasyML平台一直登陆不了。今天在win10上尝试了下可以登陆平台。但是运行样例的时候oozie好像就挂了。
以下是我oozie里面翻出来的错误日志：
```
2017-06-20 08:07:46,741 ERROR ShareLibService:536 - SERVER[hadoop-master] USER[-] GROUP[-] Not able to cache shareLib. Admin need to issue oozlie cli command to update sharelib.
java.lang.NullPointerException
        at org.apache.oozie.service.ShareLibService.init(ShareLibService.java:108)
        at org.apache.oozie.service.Services.setServiceInternal(Services.java:368)
        at org.apache.oozie.service.Services.setService(Services.java:354)
        at org.apache.oozie.service.Services.loadServices(Services.java:287)
        at org.apache.oozie.service.Services.init(Services.java:208)
        at org.apache.oozie.servlet.ServicesLoader.contextInitialized(ServicesLoader.java:45)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4206)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4705)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:601)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:675)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:601)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1317)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:840)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
        at org.apache.catalina.core.StandardService.start(StandardService.java:525)
        at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
```
另外想问下，你们目前在哪些系统平台上进行过安装测试？

**Comment by sinllychen** [comment]
@czs0x55aa  您好，问一下，您在您的docker  hadoop-master容器里面运行
```
oozie admin -oozie http://hadoop-master:11000/oozie -status 
System mode:NORMAL //显示正常结果
```
这个命令是正常的吗？

您的Docker是在ubuntu系统上安装的还是在windows系统上安装的呢？

我们自己在windows平台以及ubuntu平台的Docker上安装都是成功的。

**Comment by czs0x55aa** [comment]
@sinllychen 
运行过`oozie admin -oozie http://hadoop-master:11000/oozie -status `，输出是正常的。
我在win10和ubuntu 16.04上都安装过。
按照QuickStart的流程，安装过程中都没有出现错误提示。
运行EasyML平台时出现了不同的错误....

**Comment by nkzhlee** [comment]
请问是什么错误呢？有没有log截图，我们定位一下错误。

**Comment by czs0x55aa** [comment]
@nkxujun 你好
在ubuntu上部署完环境，进入`http://hadoop-master:18080/EMLStudio`，账号登陆时失败。找了tomcat的日志如下。
```
Jun-2017 12:38:32.760 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
17-Jun-2017 12:38:32.760 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
17-Jun-2017 12:39:05.943 SEVERE [http-nio-18080-exec-4] org.apache.catalina.core.ApplicationContext.log Exception while dispatching incoming RPC call
 com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract eml.studio.shared.model.Account eml.studio.client.rpc.AccountService.login(eml.studio.shared.model.Acco
unt)' threw an unexpected exception: java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
        at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2277)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:811)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1254)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
        at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at eml.studio.server.util.XMLUtil.read(XMLUtil.java:58)
        at eml.studio.server.constant.Constants.<clinit>(Constants.java:49)
        at eml.studio.server.db.BaseDao.getConnection(BaseDao.java:44)
        at eml.studio.server.db.BaseDao.<clinit>(BaseDao.java:31)
        at eml.studio.server.rpc.AccountServiceImpl.login(AccountServiceImpl.java:236)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
        ... 27 more
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        ... 54 more
```
看起来好像是RPC有关（我确认过mysql运行正常）。另外，我尝试了在IDEA里运行的话是不会报这个异常的（可以正常登陆），但是执行程序会出现之前的权限问题。

今天在win10上重新部署了一次，EasyML平台登陆正常（没有RPC的问题），执行任务的时候oozie似乎直接挂掉了，下面是oozie的log里报的异常
```
2017-06-20 08:07:46,741 ERROR ShareLibService:536 - SERVER[hadoop-master] USER[-] GROUP[-] Not able to cache shareLib. Admin need to issue oozlie cli command to update sharelib.
java.lang.NullPointerException
        at org.apache.oozie.service.ShareLibService.init(ShareLibService.java:108)
        at org.apache.oozie.service.Services.setServiceInternal(Services.java:368)
        at org.apache.oozie.service.Services.setService(Services.java:354)
        at org.apache.oozie.service.Services.loadServices(Services.java:287)
        at org.apache.oozie.service.Services.init(Services.java:208)
        at org.apache.oozie.servlet.ServicesLoader.contextInitialized(ServicesLoader.java:45)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4206)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4705)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:601)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:675)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:601)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1317)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:840)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
        at org.apache.catalina.core.StandardService.start(StandardService.java:525)
        at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
```

**Comment by thincamel** [comment]
@sinllychen  启动没有什么额外的异常，和QuickStart里面的一样，但就是运行不起来

Error: IO_ERROR : java.net.ConnectException: Connection refused
job: 0000000-170623082616978-oozie-root-W
Tomcat started.

**Comment by sinllychen** [comment]
@thincamel  您好，请问下您是什么运行不起来呢？是oozie还是EML的首页？，IO_ERROR这个问题可以忽略，是网络连接不稳定原因，不影响oozie和tomcat的启动。

**Comment by sinllychen** [comment]
@czs0x55aa  
关于上述登录失败问题，是由于工程所依赖的xml-api.jar包的版本问题造成的。在maven依赖中，oozie client和dom4j都包含了xml-api的不同版本的包。上述错误是因为由于包冲突，默认采用了xml-apis1.0.b2 这个包，这个包版本太低会出现上述错误。
![xml_version](https://user-images.githubusercontent.com/7518364/27575276-ca25b584-5b4b-11e7-9a95-f7286ffd7c3f.png)

目前我们已经在pom中exclude dom4j的低版本的包，并进行重新打包，更新至网盘。您可以在 [google drive disk](https://drive.google.com/open?id=0B5Lj6qkCMBbFWW5uYlJwb2drb1k) or [Baidu Cloud](https://pan.baidu.com/s/1jH6SToy) 的/cluster/config 目录下下载最新的EMLStudio.war包，并将该包通过以下命令拷贝到hadoop-master容器的tomcat目录下重新部署即可。

`docker cp your_dir/EMLStudio.war hadoop-master:/usr/local/tomcat/webapps/    //Copy file from your own entity machine to docker continer`

同时我们已更新pom.xml文件在github工程中，您可以pull一下我们的代码。
![123456](https://user-images.githubusercontent.com/7518364/27575577-dcf0b708-5b4c-11e7-86eb-9597b9780307.png)

**Comment by sinllychen** [comment]
@thincamel  
关于您所说描述的：

> 参照完成了部署，但oozie服务以及对应页面无法访问
> 执行oozie 命令：
> root@hadoop-master:~# oozie admin -oozie http://hadoop-master:11000/oozie -status
> Error: IO_ERROR : java.net.ConnectException: Connection refused

您可以按照下述方式重启Oozie。进入Hadoop-master容器，先后执行以下命令，完成Oozie重启
>     rm -rf $OOZIE_HOME/logs/*    //Clear log directory
>     rm -rf $OOZIE_HOME/oozie-server/logs/*    //Clear log directory
>     rm -rf $OOZIE_HOME/oozie-server/temp/*    //Clear temp directory
>     rm -rf $OOZIE_HOME/oozie-server/webapps/oozie/     //Delete oozie 
>     rm -rf $OOZIE_HOME/oozie-server/webapps/oozie.war    //Delete oozie.war
>     ./root/start-oozie.sh    //Rerun the start script about oozie

**Comment by zuochenbigdata** [comment]
还是通过idea编译的那个网页运行吧。
你用http://hadoop-master:18080/EMLStudio/  去访问的话，执行结果的文件不能download下来，会提示404的。用idea编译的那个网页就没问题。

**Comment by sinllychen** [comment]
@zuochenbigdata  恩对的，这个现在会有这个问题，我们正在修复。

**Comment by markgui** [comment]
@sinllychen 你好，我从百度云盘下载了EML.zip, 里面有有mysql的镜像包mysql_eml.tar，
但执行 docker import mysql_eml.tar ，包下面这个错误：
Error response from daemon: Error processing tar file(exit status 1): archive/tar: invalid tar header
是这个tar包的版本有问题吗，还是其它什么原因呢？ 谢谢~~

**Comment by sinllychen** [comment]
@markgui  导入镜像文件的命令是：`docker load --input mysql_eml.tar` 你尝试用这个命令试下。

**Comment by markgui** [comment]
@sinllychen  这个导入命令也试过了 ，错误信息是：
Error processing tar file(exit status 1): archive/tar: invalid tar header
应该是一个错误。网上有说是docker版本的原因，我的docker version 是17.06.0-ce

**Comment by sinllychen** [comment]
@markgui  您好，这是我们docker版本的信息。系统是centos7.0
![image](https://user-images.githubusercontent.com/7518364/29653493-9c22d9dc-88dc-11e7-849a-222d8ab3d656.png)

**Comment by gsscsd** [comment]
@sinllychen  您好，关于hosts配置不太懂
![Uploading 选区_007.png…](http://owz4myn7b.bkt.clouddn.com/%E9%80%89%E5%8C%BA_008.png)
这里的hosts是指修改docker里的/etc/hosts吗？如果是默认状态下，那么hosts又应该是什么？192.168.99.100吗？而且，Hadoop，mysql都是一个ip吗？

**Comment by sinllychen** [comment]
@gsscsd 您好，如果你用Windows的浏览器访问你部署的系统，那么需要修改你windows的host，host中的ip为你ubuntu系统的ip。如果你用ubuntu的浏览器访问你部署的系统，那么需要修改的是你ubuntu的host

**Comment by gsscsd** [comment]
@sinllychen 您好，设置hosts之后，出现这种错误？
![ff](http://owzdb6ojd.bkt.clouddn.com/17-9-29/78278325.jpg)
![ff](http://owzdb6ojd.bkt.clouddn.com/17-9-29/80163467.jpg)

**Comment by sinllychen** [comment]
@gsscsd 您好，您这个问题是因为容器里面的ssh服务没有启动，请进入各个容器，验证一下ssh服务是否启动，启动hadoop及oozie之前必须确保ssh服务是联通的。具体验证方式请参考QuickStart.md中的`Confirm the connectivity between containers` 这一章节

**Comment by skytianyu** [comment]
您好  我到了这一步 
root@hadoop-master:~# oozie admin -oozie http://hadoop-master:11000/oozie/ -status
Error: IO_ERROR : java.net.ConnectException: Connection refused
老连接不上 
rm -rf $OOZIE_HOME/logs/*    //Clear log directory
rm -rf $OOZIE_HOME/oozie-server/logs/*    //Clear log directory
rm -rf $OOZIE_HOME/oozie-server/temp/*    //Clear temp directory
rm -rf $OOZIE_HOME/oozie-server/webapps/oozie/     //Delete oozie 
rm -rf $OOZIE_HOME/oozie-server/webapps/oozie.war    //Delete oozie.war
./root/start-oozie.sh    //Rerun the start script about oozie
进行了这些操作后 还是连接不上 前面的HDFS和最后的主页面都能打开就是oozie服务页面打不开，请问该怎么解决？

**Comment by skytianyu** [comment]
@sinllychen

**Comment by sinllychen** [comment]
@skytianyu 您好，问一下，您的oozie数据库初始化了吗？启动过程中应该还有别的错误吗？麻烦你仔细看下，我感觉应该不止最后一个connection refused的错。

**Comment by skytianyu** [comment]
@sinllychen 谢谢 是我自己忘记初始化了 现在可以运行了 感谢....

**Comment by sinllychen** [comment]
@skytianyu 好的

**Comment by SMonkeyKing** [comment]
执行sh init_mysql.sh，提示【ERROR 1045】：Access denied for user “root@localhost”
