### ISSUE TITLE
build

### ISSUE THREAD

**Issue by falltodis** [ICT-BDA/EasyML#14]
编译的时候抛出如下异常，是否还需要其他额外的配置？
```
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.RuntimeException: not found: includeSourceMapUrl
	at com.google.gwt.dev.codeserver.Recompiler.overrideConfig(Recompiler.java:630)
	at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:499)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:204)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:192)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:151)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:104)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:666)
	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:810)
	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:551)
```

**Comment by sinllychen** [comment]
您好，想问下您的问题是在进行maven编译出问题，还是在gwt compile出问题，还是在gwt运行工程时出问题呢？

**Comment by falltodis** [comment]
gwt编译，强烈要求不用gwt，太老了，资料都找不到了

**Comment by sinllychen** [comment]
您好，感谢您的建议，GWT的资料网上是相对于别的框架较少，您可以去google上进行一些相关资料的查询，由于我们目前工程里面大部分的前端核心代码都还依赖与GWT这个框架，所以短时间内还无法替换这个框架。
       关于您上述遇到的问题，我们之前编译的时候没有遇到过此类问题，但我看了下日志，感觉应该是某些包缺失造成的，但是从日志内容还无法看出具体是什么包。麻烦您重新进行maven clean，maven build操作看是否会有类似问题，若还有，请检查一下，这个链接https://github.com/ICT-BDA/EasyML/tree/master/lib/eml  和 pom.xml中gwt相关的包是否在您的本地仓库中下载成功。
       如还有此类问题，我们再一起看下，多谢！
