### ISSUE TITLE
单机版问题

### ISSUE THREAD

**Issue by skytianyu** [ICT-BDA/EasyML#16]
您好，我把项目导入后，跑了一下（IDEA跑的），页面能打开，但是点击登录提示密码错误，还有点击注册还有游客登录都没反应。我看了一下IEDA下面有这个错误：
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1121)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:357)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2482)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2519)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2304)
大体截取了一部分，请问是我没配置好，还是有其他的错误。

**Comment by sinllychen** [comment]
@skytianyu 您好，应该是您的MySQL环境出了问题，请检查Mysql数据库能否正常访问且里面的各个表是否存在且有数据。具体Mysql数据库初始化脚本请到[google drive disk](https://drive.google.com/open?id=0B5Lj6qkCMBbFWW5uYlJwb2drb1k) or [Baidu Cloud](https://pan.baidu.com/s/1bpw72Ir) 中下载。

**Comment by skytianyu** [comment]
好的 谢啦 我去看下~~
