### ISSUE TITLE
提交任务后，后台Oozie出现org.apache.oozie.action.ActionExecutor.convertException错误

### ISSUE THREAD

**Issue by w-sorley** [ICT-BDA/EasyML#24]
你好，麻烦我想问一下，我按照quicklystart的步骤搭建好了环境，第一次可以正常运行，但是以后按照同样的步骤，在提交任务后会出现任务执行错误，后台看了一下oozie也运行正常，能不能麻烦您帮我看一下什么原因。
oozie的执行日志如下：
2017-07-26 06:23:24,857  WARN ParameterVerifier:542 - SERVER[hadoop-master] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] The application does not define formal parameters in its XML definition
2017-07-26 06:23:24,874  WARN LiteWorkflowAppService:542 - SERVER[hadoop-master] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] libpath [/EML/oozie/APP-PATH-f34582f8-4948-4fc5-84d3-44337e03b1c2/lib] does not exist
2017-07-26 06:23:25,040  INFO ActionStartXCommand:539 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@:start:] Start action [0000004-170726060341179-oozie-root-W@:start:] with user-retry state : userRetryCount [0], userRetryMax [0], userRetryInterval [10]
2017-07-26 06:23:25,041  WARN ActionStartXCommand:542 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@:start:] [***0000004-170726060341179-oozie-root-W@:start:***]Action status=DONE
2017-07-26 06:23:25,041  WARN ActionStartXCommand:542 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@:start:] [***0000004-170726060341179-oozie-root-W@:start:***]Action updated in DB!
2017-07-26 06:23:25,241  INFO ActionStartXCommand:539 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@LibSVM2LabeledPoint-15bc2b9f8ca-3180] Start action [0000004-170726060341179-oozie-root-W@LibSVM2LabeledPoint-15bc2b9f8ca-3180] with user-retry state : userRetryCount [0], userRetryMax [0], userRetryInterval [10]
2017-07-26 06:23:25,339  WARN ActionStartXCommand:542 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@LibSVM2LabeledPoint-15bc2b9f8ca-3180] Error starting action [LibSVM2LabeledPoint-15bc2b9f8ca-3180]. ErrorType [ERROR], ErrorCode [IndexOutOfBoundsException], Message [IndexOutOfBoundsException: Index: 0, Size: 0]
org.apache.oozie.action.ActionExecutorException: IndexOutOfBoundsException: Index: 0, Size: 0
	at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:401)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.submitLauncher(JavaActionExecutor.java:915)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.start(JavaActionExecutor.java:1071)
	at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:217)
	at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:62)
	at org.apache.oozie.command.XCommand.call(XCommand.java:280)
	at org.apache.oozie.service.CallableQueueService$CompositeCallable.call(CallableQueueService.java:323)
	at org.apache.oozie.service.CallableQueueService$CompositeCallable.call(CallableQueueService.java:252)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:174)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.addSystemShareLibForAction(JavaActionExecutor.java:545)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.addAllShareLibs(JavaActionExecutor.java:637)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.setLibFilesArchives(JavaActionExecutor.java:628)
	at org.apache.oozie.action.hadoop.JavaActionExecutor.submitLauncher(JavaActionExecutor.java:822)
	... 10 more
2017-07-26 06:23:25,340  WARN ActionStartXCommand:542 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@LibSVM2LabeledPoint-15bc2b9f8ca-3180] Setting Action Status to [DONE]
2017-07-26 06:23:25,460  INFO ActionEndXCommand:539 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@LibSVM2LabeledPoint-15bc2b9f8ca-3180] ERROR is considered as FAILED for SLA
2017-07-26 06:23:25,615  INFO ActionStartXCommand:539 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@fail] Start action [0000004-170726060341179-oozie-root-W@fail] with user-retry state : userRetryCount [0], userRetryMax [0], userRetryInterval [10]
2017-07-26 06:23:25,615  WARN ActionStartXCommand:542 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@fail] [***0000004-170726060341179-oozie-root-W@fail***]Action status=DONE
2017-07-26 06:23:25,615  WARN ActionStartXCommand:542 - SERVER[hadoop-master] USER[root] GROUP[-] TOKEN[] APP[Examples of distributed abalone age prediction] JOB[0000004-170726060341179-oozie-root-W] ACTION[0000004-170726060341179-oozie-root-W@fail] [***0000004-170726060341179-oozie-root-W@fail***]Action updated in DB!

**Comment by sinllychen** [comment]
您好，问一下，您此后提交的任务也是通过clone已有的任务执行的吗？

**Comment by w-sorley** [comment]
嗯，是的。我现在重新搭建了一遍环境，现在还没有遇到这个问题。

**Comment by sinllychen** [comment]
@w-sorley 你再试试看看。

**Comment by yizt** [comment]
@sinllychen 请问使用手册什么时候可以出来？谢谢！

**Comment by sinllychen** [comment]
@yizt  您好，请参考wiki：https://github.com/ICT-BDA/EasyML/wiki/EasyML-User's-Guide。多谢！

**Comment by yizt** [comment]
@sinllychen  hi, 能不能下载你们官网上的program? 还有git上开源的是web工程，请问你们的后台工程会开源么？

**Comment by sinllychen** [comment]
@yizt 您好，我们的program您可以在我们对外网站上下载二进制包，算法部分的源码我们没有开放。git上开源的是整个EML系统的代码，包括前段和后端。
