### ISSUE TITLE
导入工程出错，maven clean 出现错误

### ISSUE THREAD

**Issue by stefanxinhong** [ICT-BDA/EasyML#27]
#18 进行到marven clean时，出现以下错误，主要集中在pom.xml文件中

> [INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.systemPath' for eml:typeparser:jar should not point at files within the project directory, ${project.basedir}/lib/typeparser-1.0.jar will be unresolvable by dependent projects @ line 134, column 16
[WARNING] 'dependencies.dependency.systemPath' for eml:uploader:jar should not point at files within the project directory, ${project.basedir}/lib/uploader-1.1.0.jar will be unresolvable by dependent projects @ line 146, column 16
[WARNING] 'dependencies.dependency.systemPath' for eml:gwt-links:jar should not point at files within the project directory, ${project.basedir}/lib/gwt-links-1.3.jar will be unresolvable by dependent projects @ line 153, column 16
[ERROR] 'dependencies.dependency.systemPath' for jdk.tools:jdk.tools:jar must specify an absolute path but is ${JAVA_HOME}/lib/tools.jar @ line 160, column 16
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project eml:EMLstudio:0.1 (/home/stefan/KD/EasyML-master/pom.xml) has 1 error
**[ERROR]     'dependencies.dependency.systemPath' for jdk.tools:jdk.tools:jar must specify an absolute path but is ${JAVA_HOME}/lib/tools.jar @ line 160, column 16**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

``

**Comment by sinllychen** [comment]
@stefanxinhong  麻烦您检查一下JRE System Library默认加入的是否是JRE，如果是JRE，需要把JRE替换为JDK。如图所示为替换后的JDK：
![image](https://user-images.githubusercontent.com/7518364/30535856-457e6024-9c96-11e7-851f-bc6cc6f8f258.png)

**Comment by stefanxinhong** [comment]
@sinllychen 修改过后还是不行，截图如下
`[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for eml:EMLstudio:war:0.1
[WARNING] 'dependencies.dependency.systemPath' for eml:typeparser:jar should not point at files within the project directory, ${project.basedir}/lib/typeparser-1.0.jar will be unresolvable by dependent projects @ line 134, column 16
[WARNING] 'dependencies.dependency.systemPath' for eml:uploader:jar should not point at files within the project directory, ${project.basedir}/lib/uploader-1.1.0.jar will be unresolvable by dependent projects @ line 146, column 16
[WARNING] 'dependencies.dependency.systemPath' for eml:gwt-links:jar should not point at files within the project directory, ${project.basedir}/lib/gwt-links-1.3.jar will be unresolvable by dependent projects @ line 153, column 16
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building EasyML 0.1
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/gwt-maven-plugin/2.5.0/gwt-maven-plugin-2.5.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.427 s
[INFO] Finished at: 2017-09-18T22:05:52+08:00
[INFO] Final Memory: 7M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.codehaus.mojo:gwt-maven-plugin:2.5.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:gwt-maven-plugin:jar:2.5.0: Could not transfer artifact org.codehaus.mojo:gwt-maven-plugin:pom:2.5.0 from/to central (https://repo.maven.apache.org/maven2): connect timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
`
![screenshot from 2017-09-18 22-09-03](https://user-images.githubusercontent.com/23147143/30546197-822064a0-9cbe-11e7-8a2e-60eb7e310aef.png)
![screenshot from 2017-09-18 22-09-17](https://user-images.githubusercontent.com/23147143/30546198-82214df2-9cbe-11e7-8d35-17dc9881e1a1.png)

**Comment by sinllychen** [comment]
@stefanxinhong 您好，上述方式在windows系统上测试过是没问题的。看了下您的JDK路径，您这个应该是在linux或者centos系统下吧。在linux系统下的我们倒是没有测试过。不确定行不行。这个问题可能需要您那边自己看下了。你的Linux系统有JAVA_HOME的环境变量吗？

顺带问下您用的是idea还是eclipse编译器呢？

**Comment by sinllychen** [comment]
@stefanxinhong 如果是IDEA编译器，请把那个tools的dependency注释掉就行了。

**Comment by stefanxinhong** [comment]
@sinllychen 
使用的是linux系统，eclipse编译器，JAVA_HOME的环境变量是有的，现在搞不清楚问题出现在什么地方，如果在windows测试是没有问题的，我就换一下系统试一下

**Comment by stefanxinhong** [comment]
@sinllychen 在windows10下，进行到gwt:compile步报错，log信息如下

> [INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for eml:EMLstudio:war:0.1
[WARNING] 'dependencies.dependency.systemPath' for eml:typeparser:jar should not point at files within the project directory, ${project.basedir}/lib/typeparser-1.0.jar will be unresolvable by dependent projects @ line 134, column 16
[WARNING] 'dependencies.dependency.systemPath' for eml:uploader:jar should not point at files within the project directory, ${project.basedir}/lib/uploader-1.1.0.jar will be unresolvable by dependent projects @ line 146, column 16
[WARNING] 'dependencies.dependency.systemPath' for eml:gwt-links:jar should not point at files within the project directory, ${project.basedir}/lib/gwt-links-1.3.jar will be unresolvable by dependent projects @ line 153, column 16
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building EasyML 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- gwt-maven-plugin:2.5.0:compile (default-cli) @ EMLstudio ---
[WARNING] Don't declare gwt-dev as a project dependency. This may introduce complex dependency conflicts
[ERROR] 九月 19, 2017 10:55:11 下午 java.util.prefs.WindowsPreferences <init>
[ERROR] 警告: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[INFO] Loading inherited module 'eml.studio.EMLStudio'
[INFO]    [ERROR] A generator must extend com.google.gwt.core.ext.Generator
[INFO]    [ERROR] Line 27: Unexpected exception while processing element 'generate-with'
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefSchema$BodySchema.__generate_with_begin(ModuleDefSchema.java:483)
[INFO] 	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:606)
[INFO] 	at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:230)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:294)
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
[INFO] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:347)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:326)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:246)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:195)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:172)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:144)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:196)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:177)
[INFO]    [ERROR] Failure while parsing XML
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.util.xml.DefaultSchema.onHandlerException(DefaultSchema.java:58)
[INFO] 	at com.google.gwt.dev.util.xml.Schema.onHandlerException(Schema.java:66)
[INFO] 	at com.google.gwt.dev.util.xml.Schema.onHandlerException(Schema.java:66)
[INFO] 	at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:240)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:294)
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
[INFO] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:347)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:326)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:246)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:195)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:172)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:144)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:196)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:177)
[INFO]    [ERROR] Unexpected error while processing XML
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:371)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:326)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:246)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:195)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:172)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:144)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:196)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:177)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.237 s
[INFO] Finished at: 2017-09-19T22:55:11+08:00
[INFO] Final Memory: 13M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.5.0:compile (default-cli) on project EMLstudio: Command [[
[ERROR] C:\Program Files\Java\jdk1.7.0_80\jre\bin\java -Xmx512m -classpath "D:\KD\EasyML-master\EasyML-master\target\EMLstudio-0.1\WEB-INF\classes;D:\KD\EasyML-master\EasyML-master\src\main\java;D:\KD\EasyML-master\EasyML-master\src\main\resources;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-servlet\2.5.0\gwt-servlet-2.5.0.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-codeserver\2.5.0\gwt-codeserver-2.5.0.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-user\2.5.0\gwt-user-2.5.0.jar;C:\Users\Administrator\.m2\repository\org\json\json\20090211\json-20090211.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-dev\2.5.0\gwt-dev-2.5.0.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-incubator\2.0.1\gwt-incubator-2.0.1.jar;C:\Users\Administrator\.m2\repository\com\allen-sauer\gwt\dnd\gwt-dnd\3.1.2\gwt-dnd-3.1.2.jar;C:\Users\Administrator\.m2\repository\org\apache\hadoop\hadoop-common\2.2.0\hadoop-common-2.2.0.jar;C:\Users\Administrator\.m2\repository\com\google\guava\guava\11.0.2\guava-11.0.2.jar;C:\Users\Administrator\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\Administrator\.m2\repository\commons-cli\commons-cli\1.2\commons-cli-1.2.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-math\2.1\commons-math-2.1.jar;C:\Users\Administrator\.m2\repository\xmlenc\xmlenc\0.52\xmlenc-0.52.jar;C:\Users\Administrator\.m2\repository\commons-httpclient\commons-httpclient\3.1\commons-httpclient-3.1.jar;C:\Users\Administrator\.m2\repository\commons-codec\commons-codec\1.4\commons-codec-1.4.jar;C:\Users\Administrator\.m2\repository\commons-io\commons-io\2.1\commons-io-2.1.jar;C:\Users\Administrator\.m2\repository\commons-net\commons-net\3.1\commons-net-3.1.jar;C:\Users\Administrator\.m2\repository\javax\servlet\servlet-api\2.5\servlet-api-2.5.jar;C:\Users\Administrator\.m2\repository\org\mortbay\jetty\jetty\6.1.26\jetty-6.1.26.jar;C:\Users\Administrator\.m2\repository\org\mortbay\jetty\jetty-util\6.1.26\jetty-util-6.1.26.jar;C:\Users\Administrator\.m2\repository\com\sun\jersey\jersey-core\1.9\jersey-core-1.9.jar;C:\Users\Administrator\.m2\repository\com\sun\jersey\jersey-json\1.9\jersey-json-1.9.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jettison\jettison\1.1\jettison-1.1.jar;C:\Users\Administrator\.m2\repository\stax\stax-api\1.0.1\stax-api-1.0.1.jar;C:\Users\Administrator\.m2\repository\com\sun\xml\bind\jaxb-impl\2.2.3-1\jaxb-impl-2.2.3-1.jar;C:\Users\Administrator\.m2\repository\javax\xml\bind\jaxb-api\2.2.2\jaxb-api-2.2.2.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-jaxrs\1.8.3\jackson-jaxrs-1.8.3.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-xc\1.8.3\jackson-xc-1.8.3.jar;C:\Users\Administrator\.m2\repository\com\sun\jersey\jersey-server\1.9\jersey-server-1.9.jar;C:\Users\Administrator\.m2\repository\asm\asm\3.1\asm-3.1.jar;C:\Users\Administrator\.m2\repository\tomcat\jasper-runtime\5.5.23\jasper-runtime-5.5.23.jar;C:\Users\Administrator\.m2\repository\javax\servlet\jsp\jsp-api\2.1\jsp-api-2.1.jar;C:\Users\Administrator\.m2\repository\commons-el\commons-el\1.0\commons-el-1.0.jar;C:\Users\Administrator\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;C:\Users\Administrator\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Administrator\.m2\repository\net\java\dev\jets3t\jets3t\0.6.1\jets3t-0.6.1.jar;C:\Users\Administrator\.m2\repository\commons-lang\commons-lang\2.5\commons-lang-2.5.jar;C:\Users\Administrator\.m2\repository\commons-configuration\commons-configuration\1.6\commons-configuration-1.6.jar;C:\Users\Administrator\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\Administrator\.m2\repository\commons-digester\commons-digester\1.8\commons-digester-1.8.jar;C:\Users\Administrator\.m2\repository\commons-beanutils\commons-beanutils\1.7.0\commons-beanutils-1.7.0.jar;C:\Users\Administrator\.m2\repository\commons-beanutils\commons-beanutils-core\1.8.0\commons-beanutils-core-1.8.0.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-api\1.7.5\slf4j-api-1.7.5.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-log4j12\1.7.5\slf4j-log4j12-1.7.5.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-core-asl\1.8.8\jackson-core-asl-1.8.8.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-mapper-asl\1.8.8\jackson-mapper-asl-1.8.8.jar;C:\Users\Administrator\.m2\repository\org\apache\avro\avro\1.7.4\avro-1.7.4.jar;C:\Users\Administrator\.m2\repository\com\thoughtworks\paranamer\paranamer\2.3\paranamer-2.3.jar;C:\Users\Administrator\.m2\repository\org\xerial\snappy\snappy-java\1.0.4.1\snappy-java-1.0.4.1.jar;C:\Users\Administrator\.m2\repository\com\google\protobuf\protobuf-java\2.5.0\protobuf-java-2.5.0.jar;C:\Users\Administrator\.m2\repository\org\apache\hadoop\hadoop-auth\2.2.0\hadoop-auth-2.2.0.jar;C:\Users\Administrator\.m2\repository\com\jcraft\jsch\0.1.42\jsch-0.1.42.jar;C:\Users\Administrator\.m2\repository\org\apache\zookeeper\zookeeper\3.4.5\zookeeper-3.4.5.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-compress\1.4.1\commons-compress-1.4.1.jar;C:\Users\Administrator\.m2\repository\org\tukaani\xz\1.0\xz-1.0.jar;C:\Users\Administrator\.m2\repository\org\apache\hadoop\hadoop-hdfs\2.2.0\hadoop-hdfs-2.2.0.jar;C:\Users\Administrator\.m2\repository\commons-daemon\commons-daemon\1.0.13\commons-daemon-1.0.13.jar;C:\Users\Administrator\.m2\repository\org\apache\hadoop\hadoop-annotations\2.2.0\hadoop-annotations-2.2.0.jar;C:\Users\Administrator\.m2\repository\org\apache\oozie\oozie-client\4.1.0\oozie-client-4.1.0.jar;C:\Users\Administrator\.m2\repository\com\googlecode\json-simple\json-simple\1.1\json-simple-1.1.jar;C:\Users\Administrator\.m2\repository\org\apache\activemq\activemq-client\5.8.0\activemq-client-5.8.0.jar;C:\Users\Administrator\.m2\repository\org\apache\geronimo\specs\geronimo-jms_1.1_spec\1.1.1\geronimo-jms_1.1_spec-1.1.1.jar;C:\Users\Administrator\.m2\repository\org\fusesource\hawtbuf\hawtbuf\1.9\hawtbuf-1.9.jar;C:\Users\Administrator\.m2\repository\org\apache\geronimo\specs\geronimo-j2ee-management_1.1_spec\1.0.1\geronimo-j2ee-management_1.1_spec-1.0.1.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-simple\1.6.6\slf4j-simple-1.6.6.jar;C:\Users\Administrator\.m2\repository\xerces\xercesImpl\2.10.0\xercesImpl-2.10.0.jar;C:\Users\Administrator\.m2\repository\xml-apis\xml-apis\1.4.01\xml-apis-1.4.01.jar;C:\Users\Administrator\.m2\repository\commons-fileupload\commons-fileupload\1.3.2\commons-fileupload-1.3.2.jar;C:\Users\Administrator\.m2\repository\com\sun\mail\javax.mail\1.5.6\javax.mail-1.5.6.jar;C:\Users\Administrator\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Users\Administrator\.m2\repository\org\apache\ant\ant\1.7.1\ant-1.7.1.jar;C:\Users\Administrator\.m2\repository\org\apache\ant\ant-launcher\1.7.1\ant-launcher-1.7.1.jar;C:\Users\Administrator\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;D:\KD\EasyML-master\EasyML-master\lib\typeparser-1.0.jar;C:\Users\Administrator\.m2\repository\mysql\mysql-connector-java\5.1.26\mysql-connector-java-5.1.26.jar;D:\KD\EasyML-master\EasyML-master\lib\uploader-1.1.0.jar;D:\KD\EasyML-master\EasyML-master\lib\gwt-links-1.3.jar;C:\Program Files\Java\jdk1.7.0_80\lib\tools.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-user\2.5.0\gwt-user-2.5.0.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-dev\2.5.0\gwt-dev-2.5.0.jar" com.google.gwt.dev.Compiler -logLevel INFO -style OBF -war D:\KD\EasyML-master\EasyML-master\target\EMLstudio-0.1 -localWorkers 8 -XfragmentCount -1 -gen D:\KD\EasyML-master\EasyML-master\target\.generated eml.studio.IndexPage eml.studio.EMLStudio
[ERROR] ]] failed with status 1
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by whitebear** [comment]
> @sinllychen
> 使用的是linux系统，eclipse编译器，JAVA_HOME的环境变量是有的，现在搞不清楚问题出现在什么地方，如果在windows测试是没有问题的，我就换一下系统试一下

linux 下的eclipse在debug configgurations下的maven build 菜单下的构建项的environment中添加一个JAVE_HOME对应的路径就好

**Comment by zhangsunpanpan** [comment]
> > @sinllychen
> > 使用的是linux系统，eclipse编译器，JAVA_HOME的环境变量是有的，现在搞不清楚问题出现在什么地方，如果在windows测试是没有问题的，我就换一下系统试一下
> 
> linux 下的eclipse在debug configgurations下的maven build 菜单下的构建项的environment中添加一个JAVE_HOME对应的路径就好

什么意思呢？我也时centos,eclipse,也遇到这个问题了
