### ISSUE TITLE
'Submit' a job 后，似乎写日志文件出错了，一直不能结束，点击‘Stop'后，任务结束，可以看到result

### ISSUE THREAD

**Issue by lilyturf2017** [ICT-BDA/EasyML#48]

**Comment by lilyturf2017** [comment]
部分日志
INFO: focuspanelTimer 5  CBAA152C414F00270F374EC7290A5BFD.cache.html:4224:29303
Fri Dec 01 10:24:53 GMT+800 2017 eml.studio.client.controller.DiagramController
INFO: focuspanelTimer 6  CBAA152C414F00270F374EC7290A5BFD.cache.html:4224:29303
Fri Dec 01 10:24:53 GMT+800 2017 eml.studio.client.controller.DiagramController
INFO: focuspanelTimer 7  CBAA152C414F00270F374EC7290A5BFD.cache.html:4224:29303
Fri Dec 01 10:24:53 GMT+800 2017 eml.studio.client.controller.DiagramController
INFO: focuspanelTimer 8  CBAA152C414F00270F374EC7290A5BFD.cache.html:4224:29303
Fri Dec 01 10:24:53 GMT+800 2017 eml.studio.client.controller.DiagramController
INFO: focuspanelTimer 9  CBAA152C414F00270F374EC7290A5BFD.cache.html:4224:29303
Fri Dec 01 10:25:06 GMT+800 2017 com.google.gwt.logging.client.LogConfiguration
SEVERE: Exception caught: (TypeError) : this.b.d.j is null
com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : this.b.d.j is null
	at Unknown.yl(Unknown Source)
	at Unknown.Az(Unknown Source)
	at Unknown.Ez(Unknown Source)
	at Unknown.bz(Unknown Source)
	at Unknown.Sab(Unknown Source)
	at Unknown.kv(Unknown Source)
	at Unknown.Uab(Unknown Source)
	at Unknown.dbb(Unknown Source)
	at Unknown.ihb(Unknown Source)
	at Unknown.Bib/uib<(Unknown Source)
	at Unknown.dm(Unknown Source)
	at Unknown.gm(Unknown Source)
	at Unknown.fm/<(Unknown Source)
	at Unknown.anonymous(Unknown Source)
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : this.b.d.j is null
	at Unknown.x_b(Unknown Source)
	at Unknown.Hv(Unknown Source)
	at Unknown.mz(Unknown Source)
	at Unknown.bz(Unknown Source)
	at Unknown.Sab(Unknown Source)
	at Unknown.kv(Unknown Source)
	at Unknown.Uab(Unknown Source)
	at Unknown.dbb(Unknown Source)
	at Unknown.ihb(Unknown Source)
	at Unknown.Bib/uib<(Unknown Source)
	at Unknown.dm(Unknown Source)
	at Unknown.gm(Unknown Source)
	at Unknown.fm/<(Unknown Source)
	at Unknown.anonymous(Unknown Source)  CBAA152C414F00270F374EC7290A5BFD.cache.html:4224:29303

**Comment by lilyturf2017** [comment]
在你们的平台http://159.226.40.104:18080/dev 上  Create a job后，也无法Submit, 日志：
Fri Dec 01 10:36:49 GMT+800 2017 bda.studio.client.graph.OozieGraphBuilder
INFO: add node LibSVM2LabeledPoint-1600feea4a0-0662 add node LibSVM2LabeledPoint  C5C951B7F1108616EC5F2B70B4B8AF61.cache.html:4548:14143
Fri Dec 01 10:36:49 GMT+800 2017 bda.studio.client.graph.OozieGraphBuilder
INFO: add node X 1313 add node Y 362  C5C951B7F1108616EC5F2B70B4B8AF61.cache.html:4548:14143
Fri Dec 01 10:36:49 GMT+800 2017 bda.studio.client.graph.OozieGraphBuilder
INFO: !!! load end   C5C951B7F1108616EC5F2B70B4B8AF61.cache.html:4548:14143
Fri Dec 01 10:36:49 GMT+800 2017 com.google.gwt.logging.client.LogConfiguration
SEVERE: Exception caught: (TypeError) : a.d.j is null
com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : a.d.j is null
	at Unknown.sg(Unknown Source)
	at Unknown.GAb(Unknown Source)
	at Unknown.KAb(Unknown Source)
	at Unknown.hAb(Unknown Source)
	at Unknown.ax(Unknown Source)
	at Unknown.pwb(Unknown Source)
	at Unknown.cx(Unknown Source)
	at Unknown.nx(Unknown Source)
	at Unknown.Zic(Unknown Source)
	at Unknown.skc/lkc<(Unknown Source)
	at Unknown.pnb(Unknown Source)
	at Unknown.snb(Unknown Source)
	at Unknown.rnb/<(Unknown Source)
	at Unknown.anonymous(Unknown Source)
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : a.d.j is null
	at Unknown.$r(Unknown Source)
	at Unknown.cu(Unknown Source)
	at Unknown.Mwb(Unknown Source)
	at Unknown.sAb(Unknown Source)
	at Unknown.hAb(Unknown Source)
	at Unknown.ax(Unknown Source)
	at Unknown.pwb(Unknown Source)
	at Unknown.cx(Unknown Source)
	at Unknown.nx(Unknown Source)
	at Unknown.Zic(Unknown Source)
	at Unknown.skc/lkc<(Unknown Source)
	at Unknown.pnb(Unknown Source)
	at Unknown.snb(Unknown Source)
	at Unknown.rnb/<(Unknown Source)
	at Unknown.anonymous(Unknown Source)  C5C951B7F1108616EC5F2B70B4B8AF61.cache.html:4548:14143

**Comment by sinllychen** [comment]
@lilyturf2017 您好，之前平台上进行版本更新之后有一个BUG，目前已经修复，您可以再尝试下~
