### ISSUE TITLE
求大神：在导入平台没有的sklearn模块显示下面错误，请问怎么解决，对于平台没有的模块怎么办？

### ISSUE THREAD

**Issue by leafage-autumn** [ICT-BDA/EasyML#90]
Traceback (most recent call last):
  File "Logistic_regression_demo_03.py", line 13, in <module>
    from sklearn import datasets 
  File "/usr/local/hadoop/tmp/nm-local-dir/usercache/root/appcache/application_1543824764893_0001/container_1543824764893_0001_01_000002/sklearn/__init__.py", line 63, in <module>
    from . import __check_build
  File "/usr/local/hadoop/tmp/nm-local-dir/usercache/root/appcache/application_1543824764893_0001/container_1543824764893_0001_01_000002/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/usr/local/hadoop/tmp/nm-local-dir/usercache/root/appcache/application_1543824764893_0001/container_1543824764893_0001_01_000002/sklearn/__check_build/__init__.py", line 41, in raise_build_error
    %s""" % (e, local_dir, ''.join(dir_content).strip(), msg))
ImportError: No module named _check_build
___________________________________________________________________________
Contents of /usr/local/hadoop/tmp/nm-local-dir/usercache/root/appcache/application_1543824764893_0001/container_1543824764893_0001_01_000002/sklearn/__check_build:
__init__.py               __pycache__               _check_build.cp36-win_amd64.pyd
setup.py                  __init__.pyc
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
mv: cannot stat 'B6ED14D4-A27C-476E-B10D-B9A07A8D6612': No such file or directory
mv: cannot stat '98A50D03-28DF-48F1-91D6-E788D587714C': No such file or directory

**Comment by sinllychen** [comment]
@leafage-autumn 你去集群里面所有的机器上安装一下scikit-learn就行了。
